name: "Combine Dependabot PRs"
on:
  schedule:
    - cron: '*/5 * * * *'
  
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: maadhattah/combine-dependabot-prs@main
        with:
          branchPrefix: "task"
          mustBeGreen: true
          combineBranchName: combined-prs
          ignoreLabel: nocombine
          baseBranch: main
          openPR: true
