name: "Combine Dependabot PRs"
# on:
#   workflow_dispatch:

on:
  schedule:
    - cron: '*/5 * * * *'
    
  workflow_dispatch:

permissions:
  pull-requests: write
  repository-projects: write

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maadhattah/combine-dependabot-prs@main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: combined-prs
          ignoreLabel: nocombine
          baseBranch: dev
          openPR: true
          githubToken: ${{ secrets.MY_TOKEN }}
